name: runpyscript

on:
    workflow_dispatch:

jobs:
    runpyscipt:
        runs-on: ubuntu-latest
                
        steps:
            - name: buildrepo
              uses: actions/checkout@v4

            - name: set Python env
              uses: actions/setup-python@v5
              with:
                    python-version: "3.11"
            
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pandas
              
            - name: run python script file
              working-directory: FirstFolder
              run: python first.py  
            

