name: runPythonandPrint

on: 
    workflow_dispatch:

jobs:
    runpyscript:
        runs-on: ubuntu-latest

        steps:
            - name: build repo
              uses: actions/checkout@v4

            - name: setup python env
              uses: actions/setup-python@v5
              with:
                    python-version: "3.11"
            
            - name: run python script file
              working-directory: FirstFolder
              run: python prinvariable.py "Hello there"                     


